/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as LivraisonRouteImport } from './routes/livraison'
import { Route as MesCommandesRouteImport } from './routes/mes-commandes'
import { Route as ApiPublicMoneyfusionWebhookRouteImport } from './routes/api/public/moneyfusion/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonRoute = LivraisonRouteImport.update({
  id: '/livraison',
  path: '/livraison',
  getParentRoute: () => rootRouteImport,
} as any)
const MesCommandesRoute = MesCommandesRouteImport.update({
  id: '/mes-commandes',
  path: '/mes-commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMoneyfusionWebhookRoute =
  ApiPublicMoneyfusionWebhookRouteImport.update({
    id: '/api/public/moneyfusion/webhook',
    path: '/api/public/moneyfusion/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commande': typeof CommandeRoute
  '/compte': typeof CompteRoute
  '/livraison': typeof LivraisonRoute
  '/mes-commandes': typeof MesCommandesRoute
  '/api/public/moneyfusion/webhook': typeof ApiPublicMoneyfusionWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commande': typeof CommandeRoute
  '/compte': typeof CompteRoute
  '/livraison': typeof LivraisonRoute
  '/mes-commandes': typeof MesCommandesRoute
  '/api/public/moneyfusion/webhook': typeof ApiPublicMoneyfusionWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commande': typeof CommandeRoute
  '/compte': typeof CompteRoute
  '/livraison': typeof LivraisonRoute
  '/mes-commandes': typeof MesCommandesRoute
  '/api/public/moneyfusion/webhook': typeof ApiPublicMoneyfusionWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commande'
    | '/compte'
    | '/livraison'
    | '/mes-commandes'
    | '/api/public/moneyfusion/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commande'
    | '/compte'
    | '/livraison'
    | '/mes-commandes'
    | '/api/public/moneyfusion/webhook'
  id:
    | '__root__'
    | '/'
    | '/commande'
    | '/compte'
    | '/livraison'
    | '/mes-commandes'
    | '/api/public/moneyfusion/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandeRoute: typeof CommandeRoute
  CompteRoute: typeof CompteRoute
  LivraisonRoute: typeof LivraisonRoute
  MesCommandesRoute: typeof MesCommandesRoute
  ApiPublicMoneyfusionWebhookRoute: typeof ApiPublicMoneyfusionWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraison': {
      id: '/livraison'
      path: '/livraison'
      fullPath: '/livraison'
      preLoaderRoute: typeof LivraisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-commandes': {
      id: '/mes-commandes'
      path: '/mes-commandes'
      fullPath: '/mes-commandes'
      preLoaderRoute: typeof MesCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/moneyfusion/webhook': {
      id: '/api/public/moneyfusion/webhook'
      path: '/api/public/moneyfusion/webhook'
      fullPath: '/api/public/moneyfusion/webhook'
      preLoaderRoute: typeof ApiPublicMoneyfusionWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandeRoute: CommandeRoute,
  CompteRoute: CompteRoute,
  LivraisonRoute: LivraisonRoute,
  MesCommandesRoute: MesCommandesRoute,
  ApiPublicMoneyfusionWebhookRoute: ApiPublicMoneyfusionWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
